version: '3'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    networks:
      - crm-network
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - crm-network
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
networks:
  crm-network:
    driver: bridge

